import type { Metadata } from 'next';
import { Fredoka } from 'next/font/google';

import '@/app/globals.css';
import { Sidebar } from '@/components/core/sidebar';

const sansFont = Fredoka({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${sansFont.className} text-xl antialiased`}>
        <div className='flex h-screen flex-col md:flex-row md:overflow-hidden bg-white'>
          <div className='w-full flex-none md:w-64'>
            <Sidebar />
          </div>
          <div className='flex-grow p-6 md:overflow-y-auto'>{children}</div>
        </div>
      </body>
    </html>
  );
}
